---
sources:
    - name: meter_source
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      publishers:
          #From documentation:
          # set address of Gnocchi
          # + filter out Gnocchi-related activity meters (Swift driver)
          # + set default archive policy
          #- gnocchi://?filter_project=service&archive_policy=low
          
          #Kolla-Ansbile default:
          #- gnocchi://
          - gnocchi://?archive_policy=high
